# Generated by Django 4.2 on 2023-04-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_staff_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notification',
            name='sender',
        ),
    ]
