# Generated by Django 4.2 on 2023-04-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_student_notification_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_notification',
            old_name='staff_id',
            new_name='student_id',
        ),
    ]
