# Generated by Django 4.2 on 2023-04-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='taken',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student'),
        ),
        migrations.DeleteModel(
            name='Attendance_report',
        ),
    ]
